draw_config:
  key_w: 64.0
  key_h: 58.0
  split_gap: 40.0
  n_columns: 2
  dark_mode: auto
  draw_key_sides: true
  append_colon_to_layer_header: false
parse_config:
  mark_alternate_layer_activators: true
  trans_legend:
    t: ▽
    type: trans
  raw_binding_map:
    "&cpi 1": CPI +
    "&cpi (-1)": CPI −
    "&cpi 0": CPI reset
    "&swapper": Alt+Tab
    "&swapper_back": Alt+Shift+Tab
    "&bootloader": Boot
    "&mkp MB1": MBL
    "&drag_click":
      t: MBL
      h: drag
    "&mkp MB2": MBR
    "&mkp MB3": MBM
    "&mkp MB4": Back
    "&mkp MB5": Fwd
  zmk_keycode_map:
    TAB: Tab
    ESC: Esc
    DEL: Del
    BSPC: Bksp
    RET: Enter
    SPACE: Space
    LSHFT: Shift
    RSHFT: Shift
    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    LGUI: Meta
    LANG1: Lang1
    INS: Ins
    PSCRN: PrtSc
    SEMI: ;
    SQT: "'"
    COMMA: ","
    DOT: .
    FSLH: /
    BSLH: \
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: $
    PRCNT: "%"
    CARET: ^
    AMPS: "&"
    STAR: "*"
    PLUS: +
    MINUS: "-"
    UNDER: _
    EQUAL: "="
    COLON: ":"
    GRAVE: "`"
    TILDE: "~"
    PIPE: "|"
    QMARK: "?"
    LT: <
    GT: ">"
    LPAR: (
    RPAR: )
    LBKT: "["
    RBKT: "]"
    LBRC: "{"
    RBRC: "}"
    LEFT: ←
    DOWN: ↓
    UP: ↑
    RIGHT: →
    PG_UP: PgUp
    PG_DN: PgDn
